# define a default docker image for all jobs
image: node:latest

stages:
  - deploy   # stage for deploying to environments

cache:
  paths:
    - node_modules/

deploy:development:
  stage: deploy
  script:
    - make deploy
  only:
    - master
  environment: development

deploy:production:
  stage: deploy
  script:
    - make deploy STAGE=prd
  when: manual
  only:
    - master
  environment: production
