# define a default docker image for all jobs
image: node:latest

stages:
  - deploy   # stage for deploying to environments

cache:
  paths:
    - node_modules/

deploy:development:
  stage: deploy
  script:
    - export AWS_ACCESS_KEY_ID=$DEV_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$DEV_AWS_SECRET_ACCESS_KEY
    - make deploy
  only:
    - master
  environment: development

deploy:production:
  stage: deploy
  script:
    - export AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY
    - make deploy STAGE=prd
  when: manual
  only:
    - master
  environment: production
