Resources:
  FlowsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableNames.flows}
      AttributeDefinitions:
        - AttributeName: organizationId
          AttributeType: S
        - AttributeName: id
          AttributeType: S
        - AttributeName: webhookId
          AttributeType: S
      KeySchema:
        - AttributeName: organizationId
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: ${self:custom.indexes.flows.organizationIdWebhookId}
          KeySchema:
            - AttributeName: organizationId
              KeyType: HASH
            - AttributeName: webhookId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  FlowNodesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableNames.flowNodes}
      AttributeDefinitions:
        - AttributeName: flowId
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: flowId
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

Outputs:
  FlowsTableName:
    Value: ${self:custom.tableNames.flows}
    Export:
      Name: ${self:custom.resourcesPrefix}-FlowsTableName

  FlowsTableArn:
    Value:
      !GetAtt [FlowsTable, Arn]
    Export:
      Name: ${self:custom.resourcesPrefix}-FlowsTableArn

  FlowNodesTableName:
    Value: ${self:custom.tableNames.flowNodes}
    Export:
      Name: ${self:custom.resourcesPrefix}-FlowNodesTableName

  FlowNodesTableArn:
    Value:
      !GetAtt [FlowNodesTable, Arn]
    Export:
      Name: ${self:custom.resourcesPrefix}-FlowNodesTableArn

  FlowsOrganizationIdWebhookIdIndexName:
    Value: ${self:custom.indexes.flows.organizationIdWebhookId}
    Export:
      Name: ${self:custom.resourcesPrefix}-FlowsOrganizationIdWebhookIdIndexName
